/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BooksRouteImport } from './routes/books'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GatherRouteImport } from './routes/gather'
import { Route as GiveRouteImport } from './routes/give'
import { Route as PodcastRouteImport } from './routes/podcast'
import { Route as PrayRouteImport } from './routes/pray'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as BooksIndexRouteImport } from './routes/books.index'
import { Route as BooksSlugRouteImport } from './routes/books.$slug'
import { Route as PodcastIndexRouteImport } from './routes/podcast.index'
import { Route as PodcastSlugRouteImport } from './routes/podcast.$slug'
import { Route as WatchIndexRouteImport } from './routes/watch.index'
import { Route as WatchSlugRouteImport } from './routes/watch.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GatherRoute = GatherRouteImport.update({
  id: '/gather',
  path: '/gather',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveRoute = GiveRouteImport.update({
  id: '/give',
  path: '/give',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastRoute = PodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayRoute = PrayRouteImport.update({
  id: '/pray',
  path: '/pray',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BooksRoute,
} as any)
const BooksSlugRoute = BooksSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BooksRoute,
} as any)
const PodcastIndexRoute = PodcastIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PodcastRoute,
} as any)
const PodcastSlugRoute = PodcastSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PodcastRoute,
} as any)
const WatchIndexRoute = WatchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WatchRoute,
} as any)
const WatchSlugRoute = WatchSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WatchRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/books': typeof BooksRouteWithChildren
  '/contact': typeof ContactRoute
  '/gather': typeof GatherRoute
  '/give': typeof GiveRoute
  '/podcast': typeof PodcastRouteWithChildren
  '/pray': typeof PrayRoute
  '/watch': typeof WatchRouteWithChildren
  '/books/$slug': typeof BooksSlugRoute
  '/podcast/$slug': typeof PodcastSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/books/': typeof BooksIndexRoute
  '/podcast/': typeof PodcastIndexRoute
  '/watch/': typeof WatchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gather': typeof GatherRoute
  '/give': typeof GiveRoute
  '/pray': typeof PrayRoute
  '/books/$slug': typeof BooksSlugRoute
  '/podcast/$slug': typeof PodcastSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/books': typeof BooksIndexRoute
  '/podcast': typeof PodcastIndexRoute
  '/watch': typeof WatchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/books': typeof BooksRouteWithChildren
  '/contact': typeof ContactRoute
  '/gather': typeof GatherRoute
  '/give': typeof GiveRoute
  '/podcast': typeof PodcastRouteWithChildren
  '/pray': typeof PrayRoute
  '/watch': typeof WatchRouteWithChildren
  '/books/$slug': typeof BooksSlugRoute
  '/podcast/$slug': typeof PodcastSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/books/': typeof BooksIndexRoute
  '/podcast/': typeof PodcastIndexRoute
  '/watch/': typeof WatchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/books'
    | '/contact'
    | '/gather'
    | '/give'
    | '/podcast'
    | '/pray'
    | '/watch'
    | '/books/$slug'
    | '/podcast/$slug'
    | '/watch/$slug'
    | '/books/'
    | '/podcast/'
    | '/watch/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/gather'
    | '/give'
    | '/pray'
    | '/books/$slug'
    | '/podcast/$slug'
    | '/watch/$slug'
    | '/books'
    | '/podcast'
    | '/watch'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/books'
    | '/contact'
    | '/gather'
    | '/give'
    | '/podcast'
    | '/pray'
    | '/watch'
    | '/books/$slug'
    | '/podcast/$slug'
    | '/watch/$slug'
    | '/books/'
    | '/podcast/'
    | '/watch/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BooksRoute: typeof BooksRouteWithChildren
  ContactRoute: typeof ContactRoute
  GatherRoute: typeof GatherRoute
  GiveRoute: typeof GiveRoute
  PodcastRoute: typeof PodcastRouteWithChildren
  PrayRoute: typeof PrayRoute
  WatchRoute: typeof WatchRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gather': {
      id: '/gather'
      path: '/gather'
      fullPath: '/gather'
      preLoaderRoute: typeof GatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/give': {
      id: '/give'
      path: '/give'
      fullPath: '/give'
      preLoaderRoute: typeof GiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pray': {
      id: '/pray'
      path: '/pray'
      fullPath: '/pray'
      preLoaderRoute: typeof PrayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/$slug': {
      id: '/books/$slug'
      path: '/$slug'
      fullPath: '/books/$slug'
      preLoaderRoute: typeof BooksSlugRouteImport
      parentRoute: typeof BooksRoute
    }
    '/podcast/': {
      id: '/podcast/'
      path: '/'
      fullPath: '/podcast/'
      preLoaderRoute: typeof PodcastIndexRouteImport
      parentRoute: typeof PodcastRoute
    }
    '/podcast/$slug': {
      id: '/podcast/$slug'
      path: '/$slug'
      fullPath: '/podcast/$slug'
      preLoaderRoute: typeof PodcastSlugRouteImport
      parentRoute: typeof PodcastRoute
    }
    '/watch/': {
      id: '/watch/'
      path: '/'
      fullPath: '/watch/'
      preLoaderRoute: typeof WatchIndexRouteImport
      parentRoute: typeof WatchRoute
    }
    '/watch/$slug': {
      id: '/watch/$slug'
      path: '/$slug'
      fullPath: '/watch/$slug'
      preLoaderRoute: typeof WatchSlugRouteImport
      parentRoute: typeof WatchRoute
    }
  }
}

interface BooksRouteChildren {
  BooksSlugRoute: typeof BooksSlugRoute
  BooksIndexRoute: typeof BooksIndexRoute
}

const BooksRouteChildren: BooksRouteChildren = {
  BooksSlugRoute: BooksSlugRoute,
  BooksIndexRoute: BooksIndexRoute,
}

const BooksRouteWithChildren = BooksRoute._addFileChildren(BooksRouteChildren)

interface PodcastRouteChildren {
  PodcastSlugRoute: typeof PodcastSlugRoute
  PodcastIndexRoute: typeof PodcastIndexRoute
}

const PodcastRouteChildren: PodcastRouteChildren = {
  PodcastSlugRoute: PodcastSlugRoute,
  PodcastIndexRoute: PodcastIndexRoute,
}

const PodcastRouteWithChildren =
  PodcastRoute._addFileChildren(PodcastRouteChildren)

interface WatchRouteChildren {
  WatchSlugRoute: typeof WatchSlugRoute
  WatchIndexRoute: typeof WatchIndexRoute
}

const WatchRouteChildren: WatchRouteChildren = {
  WatchSlugRoute: WatchSlugRoute,
  WatchIndexRoute: WatchIndexRoute,
}

const WatchRouteWithChildren = WatchRoute._addFileChildren(WatchRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BooksRoute: BooksRouteWithChildren,
  ContactRoute: ContactRoute,
  GatherRoute: GatherRoute,
  GiveRoute: GiveRoute,
  PodcastRoute: PodcastRouteWithChildren,
  PrayRoute: PrayRoute,
  WatchRoute: WatchRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
